export const bikeCategories = ["Mountain", "Road", "Hybrid", "Electric"];
export const bikeBrands = [
  "Yamaha",
  "KTM",
  "Honda",
  "Suzuki",
  "Kawasaki",
  "Royal Enfield",
  "BMW",
  "Triumph",
  "Zero",
  "Harley-Davidson",
  "Energica",
  "Tesla",
  "Ducati",
  "Aprilia",
  "MV Agusta",
  "Indian",
  "Hero",
  "Bajaj",
  "TVS",
  "Mahindra",
];
