export const bikeCategories = ["Mountain", "Road", "Hybrid", "Electric"];
export const bikeBrands = [
  "Yamaha",
  "Honda",
  "Suzuki",
  "Kawasaki",
  "Ducati",
  "BMW",
  "Harley Davidson",
  "Triumph",
  "KTM",
  "Aprilia",
  "MV Agusta",
  "Benelli",
  "Royal Enfield",
  "Bajaj",
  "TVS",
  "Hero",
  "Jawa",
  "Mahindra",
  "Husqvarna",
  "Indian",
  "Norton",
  "Cleveland CycleWerks",
  "UM Motorcycles",
  "CFMoto",
  "Revolt",
  "Ather",
  "Ola Electric",
  "Simple Energy",
  "Tork",
  "Ultraviolette",
  "Emflux",
  "Kabira Mobility",
  "Lectro",
  "Odysse",
  "Evolet",
  "EeVe",
  "Ampere",
  "Hero Electric",
  "Okaya",
  "Avon",
  "Tunwal",
  "Joy e-bike",
  "Lohia",
  "BGauss",
  "Detel",
  "Gemopai",
];
